name: Bug report - バグ報告
description: Something is not working correctly - 問題の報告
title: "[Bug]: "
labels: "bug"

body:
  - type: textarea
    attributes:
      label: Description - 説明
      description: >-
        A clear and concise description of what the bug is.
        報告したい問題について簡潔に説明してください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior - 期待する動作
      description: >-
        A clear and concise description of what you expected to happen.
        どのような動作を期待しているか説明してください。

  - type: input
    attributes:
      label: Pysesameos2 version (`pip show pysesameos2`)
    validations:
      required: true
  - type: input
    attributes:
      label: Python version (`python --version`)
    validations:
      required: true
  - type: input
    attributes:
      label: OS
    validations:
      required: true
  - type: input
    attributes:
      label: BlueZ version (`bluetoothctl -v`) in case of Linux

  - type: textarea
    attributes:
      label: How to Reproduce - 再現方法
      description: >-
        Please provide steps to reproduce this bug.
        報告する問題を再現する方法を教えてください。
      value: |
        1. Get package from '...'
        2. Then run '...'
        3. An error occurs.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Output - 出力された内容, 具体的な問題内容
      description: >-
        Provide the output of the steps above, including the commands
        themselves and output/traceback etc.
        再現方法について、そのコマンド文そのものを含めて
        表示された出力やエラーメッセージを貼り付けてください。
      render: sh-session
